version: '3.8'
services:
  app:
    image: natanparmigianopaganini/lp-zimprova:1.0.0
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"
    environment:
      TYPE: ${TYPE}
      PROJECT_ID: ${PROJECT_ID}
      PRIVATE_KEY_ID: ${PRIVATE_KEY_ID}
      PRIVATE_KEY: ${PRIVATE_KEY}
      CLIENT_EMAIL: ${CLIENT_EMAIL}
      CLIENT_ID: ${CLIENT_ID}
      AUTH_URI: ${AUTH_URI}
      TOKEN_URI: ${TOKEN_URI}
      AUTH_PROVIDER_X509_CERT_URL: ${AUTH_PROVIDER_X509_CERT_URL}
      CLIENT_X509_CERT_URL: ${CLIENT_X509_CERT_URL}
      PASSWORD: ${PASSWORD}
